server:
  port: 10191

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:./data/zeroq_sensor_gateway_prod;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
