log.config.path=/data/logs/prod/zeroq_sensor_gateway
log.config.app.error.name=zeroq_sensor_gateway_prod_app_error
log.config.app.warn.name=zeroq_sensor_gateway_prod_app_warn
log.config.sql.error.name=zeroq_sensor_gateway_prod_sql_error
log.config.sql.trace.name=zeroq_sensor_gateway_prod_sql_trace
